In [1]:
import pandas as pd

In [2]:
'''
Q1. Read yelp.csv into a DataFrame.
'''

'\nRead yelp.csv into a DataFrame.\n'

In [3]:
yelp_data = pd.read_csv('yelp.csv')

In [129]:
yelp_data.shape

(10000, 10)

In [5]:
'''
Q2.Create a new DataFrame that only contains the 5-star and 1-star reviews.
'''

'\nCreate a new DataFrame that only contains the 5-star and 1-star reviews.\n'

In [6]:
yelp = yelp_data[['stars','text']]

In [8]:
yelp = yelp[(yelp.stars==1) | (yelp.stars==5)]

In [9]:
'''
Q3.Split the new DataFrame into training and testing sets, using the review text as the only feature 
and the star rating as the response.
'''

'\nSplit the new DataFrame into training and testing sets, using the review text as the only feature \nand the star rating as the response.\n'

In [56]:
y=yelp.stars
X=yelp.text

In [110]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [14]:
'''
Q4.Use CountVectorizer to create document-term matrices from X_train and X_test.
Hint: If you run into a decoding error, instantiate the vectorizer with the argument decode_error='ignore'.
'''

"\nUse CountVectorizer to create document-term matrices from X_train and X_test.\nHint: If you run into a decoding error, instantiate the vectorizer with the argument decode_error='ignore'.\n"

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
vect = CountVectorizer()

In [17]:
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<3064x16825 sparse matrix of type '<type 'numpy.int64'>'
	with 237720 stored elements in Compressed Sparse Row format>

In [105]:
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1022x10374 sparse matrix of type '<type 'numpy.int64'>'
	with 74898 stored elements in Compressed Sparse Row format>

In [19]:
'''
Q5.Use Naive Bayes to predict the star rating for reviews in the testing set, and calculate the accuracy
'''

'\nUse Naive Bayes to predict the star rating for reviews in the testing set, and calculate the accuracy\n'

In [20]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn import metrics

In [85]:
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [86]:
X_train_dtm.shape

(3064, 16825)

In [88]:
y_pred_class = nb.predict(X_test_dtm)

In [89]:
X_test_dtm.shape

(1022, 16825)

In [23]:
print metrics.accuracy_score(y_test, y_pred_class)

0.918786692759


In [24]:
'''
Q6.Calculate the AUC.
Hint 1: Make sure to pass the predicted probabilities to roc_auc_score, not the predicted classes.
Hint 2: roc_auc_score will get confused if y_test contains fives and ones, so you will need to create 
a new object that contains ones and zeros instead.
'''

'\nCalculate the AUC.\nHint 1: Make sure to pass the predicted probabilities to roc_auc_score, not the predicted classes.\nHint 2: roc_auc_score will get confused if y_test contains fives and ones, so you will need to create \na new object that contains ones and zeros instead.\n'

In [25]:
y_pred_prob = nb.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([  1.00000000e+00,   9.99759874e-01,   1.00000000e+00, ...,
         1.00000000e+00,   1.05200807e-19,   9.99915316e-01])

In [27]:
y_test = y_test.map({1:0,5:1})

In [28]:
print metrics.roc_auc_score(y_test, y_pred_prob)

0.940353585141


In [30]:
print metrics.roc_auc_score(y_test, y_pred_prob)

0.940353585141


In [31]:
'''
Q7.Plot the ROC curve.
'''

'\nPlot the ROC curve.\n'

In [32]:
'''
Q8.Print the confusion matrix, and calculate the sensitivity and specificity. Comment on the results.
'''

'\nPrint the confusion matrix, and calculate the sensitivity and specificity. Comment on the results.\n'

In [33]:
print metrics.confusion_matrix(y_test, y_pred_class)

[[  0 126  58]
 [  0  25 813]
 [  0   0   0]]


In [34]:
'''
Q9. Browse through the review text for some of the false positives and false negatives. 
Based on your knowledge of how Naive Bayes works, do you have any theories about why the model 
is incorrectly classifying these reviews?
'''

'\n\n'

In [35]:
X_test[y_test < y_pred_class]

3922    Looking a cutting edge, wanting the best for e...
8379    Greatness in the form of food, just like the o...
4266    The Flower Studio far exceeded my expectations...
5577        So yummy! Strange combination but great place
537     I've been hearing about these cheesecakes from...
2175    This has to be the worst restaurant in terms o...
4556    I ate at Scramble last Friday and I have to sa...
1502    We decided to eat here on a whim. My husband g...
6434    I LOVE BURRITO EXPRESS. My fiance has been goi...
2282    Just open.  I had the roast beef sandwich and ...
2836    Cute busy place in Central Phoenix. Not hiding...
3029    I'm a big fan of Silver Mine. I have been for ...
461     I have now visited Herb n' Flavors several tim...
2155    I love to come here from time to time when I'm...
1048    Went to Fatburger with our family tonight and ...
6068    This review pertains to carnitas, and as such ...
4080    TIP #1 to Mesa-Gateway fliers: This is the ONL...
1781    If you

In [39]:
'''
Q11. Let's see how well Naive Bayes performs when all reviews are included, rather than just 1-star and 5-star reviews:
1. Define X and y using the original DataFrame from step 1. (y should contain 5 different classes.)
2. Split the data into training and testing sets.
3. Calculate the testing accuracy of a Naive Bayes model.
4. Compare the testing accuracy with the null accuracy.
5. Print the confusion matrix.
6. Comment on the results.
'''

"\nLet's see how well Naive Bayes performs when all reviews are included, rather than just 1-star and 5-star reviews:\n1. Define X and y using the original DataFrame from step 1. (y should contain 5 different classes.)\n2. Split the data into training and testing sets.\n3. Calculate the testing accuracy of a Naive Bayes model.\n4. Compare the testing accuracy with the null accuracy.\n5. Print the confusion matrix.\n6. Comment on the results.\n"

In [128]:
yelp_data.shape

(10000, 10)

In [145]:
yelp_all = yelp_data

In [147]:
d = yelp_all.stars

In [148]:
C = yelp_all.text

In [149]:
C_train, C_test, d_train, d_test = train_test_split(C, d, random_state=1)

In [150]:
C_train.shape

(7500L,)

In [152]:
vect = CountVectorizer()

In [153]:
C_train_dtm = vect.fit_transform(C_train)
C_train_dtm

<7500x25797 sparse matrix of type '<type 'numpy.int64'>'
	with 622700 stored elements in Compressed Sparse Row format>

In [154]:
C_test_dtm = vect.transform(C_test)
C_test_dtm

<2500x25797 sparse matrix of type '<type 'numpy.int64'>'
	with 200729 stored elements in Compressed Sparse Row format>

In [155]:
nb = MultinomialNB()
nb.fit(C_train_dtm, d_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [156]:
C_train_dtm.shape

(7500, 25797)

In [157]:
C_test_dtm.shape

(2500, 25797)

In [158]:
d_pred_class = nb.predict(C_test_dtm)

In [160]:
print metrics.accuracy_score(d_test, d_pred_class)

0.4712


In [166]:
print metrics.confusion_matrix(d_test, d_pred_class)

[[ 55  14  24  65  27]
 [ 28  16  41 122  27]
 [  5   7  35 281  37]
 [  7   0  16 629 232]
 [  6   4   6 373 443]]


In [167]:
d_test.shape

(2500L,)

In [168]:
'''
1. The accuracy dropped by 50% after number of values to be predicted increased
2. Number of rows and columns of a confusion matrix corresponds to the number of values to be predicted
'''

'\n1. The accuracy dropped by 50% after number of values to be predicted increased\n2. Number of rows and columns of a confusion matrix corresponds to the number of values to be predicted\n'